export const POST_REQUEST = "CREATE_REQUEST";
export const POST_SUCCESS = "CREATE_SUCCESS";
export const POST_ERROR = "CREATE_ERROR";

export const GET_REQUEST = "GET_REQUEST";
export const GET_SUCCESS = "GET_SUCCESS";
export const GET_ERROR = "GET_ERROR";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_ERROR = "UPDATE_ERROR";

export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_ERROR = "LIKE_ERROR";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_ERROR = "DELETE_ERROR";

export const AUTH = "AUTH";


export const GEN_TOKEN = "GEN_TOKEN";
export const ERROR_TOKEN = "ERROR_TOKEN";

export const LOGOUT = "LOGOUT";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const SET_SNACKBAR = "SET_SNACKBAR";

export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_NAME_ERROR = "CHANGE_NAME_ERROR"; 

export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAIL = "COMMENT_FAIL";

export const DELETE_COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "COMMENT_FAIL";

export const COMMENT_DATA_SUCCESS = "COMMENTDATA_SUCCESS";
export const COMMENT_DATA_FAIL = "COMMENTDATA_FAIL";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
